<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contacts</title>
</head>
<body>
<h1 align="center" class="mb-5">Таблица заявок</h1>
<table class="table" id="allPosts" width="100%" align="center">
    <thead>
    <tr>
        <th scope="col-4">#</th>
        <th scope="col">Имя</th>
        <th scope="col">Емайл</th>
        <th scope="col">Категория</th>
        <th scope="col">Text</th>
    </tr>
    </thead>
    <tbody>

    <?php
    require ('conectionAndFunctions.php');
    $contacts = getContacts();
    $contacts = array_reverse($contacts);
    foreach ($contacts as $contact) {
        echo '<tr>';
        echo '<th align="center"> ' . $contact["id"] . '</th>';
        echo '<td align="center">' . $contact["name"] . '</td>';
        echo '<td align="center">' . $contact["email"] . '</td>';
        echo '<td align="center">' . $contact["category"] . '</td>';
        echo '<td align="center">' . $contact["message"] . '</td>';
    }
    ?>
    </tbody>
</table>
</body>
</html>